[project]
name = "projeto-02"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dash>=3.3.0",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
]
